myobj = open("testing.txt",'w')
a=input("Enter String: ")
myobj.write(a)
myobj.seek(0)
a=input("Enter String: ")
myobj.write(a)
myobj.close()
myobj = open("testing.txt",'r')
b=myobj.read()
print(b)
myobj.seek(4)
b=myobj.read()
print(b)
myobj.close()
